const locations = [
    {
        "id": 1,
        "title": "Amstelstraat 41 (Casco Plus)",
        "neighborhood": "Amsterdam Centrum",
        "surroundings": "Bruisende centrum, near Rembrandtplein. Levendige mix of horeca, retail, high tourist and local traffic.",
        "rent": "\u20ac 4.042 / mo",
        "takeover": "\u20ac 50.000",
        "size": "60 m\u00b2 (has 4.5m2 entresol)",
        "rentableSpace": "Casco plus delivery, wide facade, large windows, seating at front, open kitchen setup behind.",
        "suitability": "High",
        "suitClass": "suit-high",
        "description": "Excellent central location. Good for a high-volume doner concept targeting nightlife and tourists.",
        "lat": 52.3662349,
        "lng": 4.8996689,
        "link": "https://horecasite.nl/advertentie/nederland/noord-holland/amsterdam/48538-id4013-nette-casco-plus-horecalocatie",
        "fastFoodDoner": "Yes",
        "casualDiningKebab": "No",
        "isFavorite": true
    },
    {
        "id": 2,
        "title": "Haarlemmerdijk 8 (Subway)",
        "neighborhood": "Amsterdam Centrum",
        "surroundings": "One of the most diverse and atmospheric shopping streets, very high foot traffic.",
        "rent": "\u20ac 3.441 / mo",
        "takeover": "\u20ac 69.000",
        "size": "73 m\u00b2",
        "rentableSpace": "Fully equipped (was Subway), 16 seats, option for small front terrace. Ready to go layout.",
        "suitability": "Very High",
        "suitClass": "suit-very-high",
        "description": "Perfect size and layout for a kebab shop. The Subway setup means the counter and kitchen flow is already optimized for fast-casual.",
        "lat": 52.3817657,
        "lng": 4.8889431,
        "link": "https://horecasite.nl/advertentie/nederland/noord-holland/amsterdam/47519-subway-op-de-haarlemmerdijk-in-amsterdam",
        "fastFoodDoner": "Yes",
        "casualDiningKebab": "No"
    },
    {
        "id": 3,
        "title": "Ceintuurbaan 210",
        "neighborhood": "De Pijp",
        "surroundings": "Levendige buurt with young residents. High traffic of cyclists and pedestrians.",
        "rent": "On Request",
        "takeover": "\u20ac 120.000",
        "size": "30 seats",
        "rentableSpace": "Warm interior, extensive kitchen at front and back. Large storage in garden.",
        "suitability": "Moderate",
        "suitClass": "suit-moderate",
        "description": "Takeover is quite high. Better for a sit-down restaurant than a quick-service kebab place.",
        "lat": 52.3521916,
        "lng": 4.8878905,
        "link": "https://horecasite.nl/advertentie/nederland/noord-holland/amsterdam/48588-karakteristiek-restaurant-in-de-pijp",
        "fastFoodDoner": "Maybe",
        "casualDiningKebab": "Yes"
    },
    {
        "id": 4,
        "title": "Eerste van der Helststraat 35 (Noosh)",
        "neighborhood": "De Pijp",
        "surroundings": "Extremely busy area right off the Albert Cuyp market. Huge mix of tourists and locals.",
        "rent": "\u20ac 5.000 / mo",
        "takeover": "\u20ac 90.000",
        "size": "75 m\u00b2",
        "rentableSpace": "Corner building, large windows, no terrace. Currently serves sandwiches.",
        "suitability": "High",
        "suitClass": "suit-high",
        "description": "Perfect size for doner, massive foot traffic, but premium pricing for rent and takeover.",
        "lat": 52.3556295,
        "lng": 4.8931947,
        "link": "https://horecasite.nl/advertentie/nederland/noord-holland/amsterdam/46394-top-onderneming-op-een-top-locatie-noosh-amsterdam-eur-90-000",
        "fastFoodDoner": "Yes",
        "casualDiningKebab": "No",
        "isFavorite": true
    },
    {
        "id": 5,
        "title": "Parnassusweg 775 (CubeHouse)",
        "neighborhood": "Zuidas",
        "surroundings": "High-end business district, new development.",
        "rent": "~ \u20ac 7.656 / mo",
        "takeover": "Casco (New)",
        "size": "245 m\u00b2",
        "rentableSpace": "New development (2025), 100 seats, terrace available. Casco state.",
        "suitability": "Moderate",
        "suitClass": "suit-moderate",
        "description": "High rent and large space. Would require a premium, large-scale dining concept to succeed here.",
        "lat": 52.3375298,
        "lng": 4.8694373,
        "link": "https://horecaspot.nl/aanbod/vastgoed-6130-the-cubehouse-amsterdam",
        "fastFoodDoner": "Yes",
        "casualDiningKebab": "Yes",
        "isFavorite": true
    },
    {
        "id": 6,
        "title": "Amstelveenseweg 53",
        "neighborhood": "Amsterdam Zuid",
        "surroundings": "Near Vondelpark, central location with high passing traffic.",
        "rent": "~ \u20ac 4.579 / mo",
        "takeover": "\u20ac 117.500",
        "size": "115 m\u00b2",
        "rentableSpace": "60 inside seats, 8 terrace seats.",
        "suitability": "High",
        "suitClass": "suit-high",
        "description": "Great location and good size, though takeover is slightly high. Terrace is a big plus.",
        "lat": 52.3541286,
        "lng": 4.8558446,
        "link": "https://horecaspot.nl/aanbod/bedrijf-5366-id-3883-bar-restaurant-met-terras-aan-de-amstelveenseweg",
        "fastFoodDoner": "Yes",
        "casualDiningKebab": "Yes"
    },
    {
        "id": 7,
        "title": "Amstel 1 (Waterlooplein)",
        "neighborhood": "Amsterdam Centrum",
        "surroundings": "Highly touristic area, close to Stopera and Waterlooplein.",
        "rent": "~ \u20ac 7.187 / mo",
        "takeover": "On Request",
        "size": "150 m\u00b2",
        "rentableSpace": "Casco unit, 80 seats, terrace possible.",
        "suitability": "Moderate",
        "suitClass": "suit-moderate",
        "description": "Premium tourist location but high rent. You need huge volume to justify the costs here.",
        "lat": 52.3676,
        "lng": 4.9015,
        "link": "https://horecaspot.nl/aanbod/bedrijf-5527-id-3909-casco-horecaruimte-unit-21-aan-het-waterlooplein-in-amsterdam",
        "fastFoodDoner": "Yes",
        "casualDiningKebab": "Yes"
    },
    {
        "id": 8,
        "title": "Keizer Karelweg 337",
        "neighborhood": "Amstelveen",
        "surroundings": "Residential neighborhood in Amstelveen.",
        "rent": "~ \u20ac 2.187 / mo",
        "takeover": "\u20ac 85.000",
        "size": "84 m\u00b2",
        "rentableSpace": "25 inside seats, 20 terrace seats.",
        "suitability": "High",
        "suitClass": "suit-high",
        "description": "Great local spot with low rent. Perfect for a neighborhood Turkish food/delivery hub.",
        "lat": 52.3074968,
        "lng": 4.8562351,
        "link": "https://horecaspot.nl/aanbod/bedrijf-6187-ideale-locatie-om-te-starten",
        "fastFoodDoner": "Yes",
        "casualDiningKebab": "Yes",
        "isFavorite": true
    },
    {
        "id": 9,
        "title": "Buitenveldertselaan 30",
        "neighborhood": "Buitenveldert",
        "surroundings": "Close to VU University and Zuidas. High concentration of students.",
        "rent": "~ \u20ac 1.810 / mo",
        "takeover": "\u20ac 80.000",
        "size": "102 m\u00b2",
        "rentableSpace": "Stylish interior, 24 inside seats, 12 terrace seats.",
        "suitability": "Very High",
        "suitClass": "suit-very-high",
        "description": "Excellent location for a doner concept due to VU proximity and low rent. Terrace is a massive bonus.",
        "lat": 52.3314626,
        "lng": 4.8682737,
        "link": "https://horecaspot.nl/aanbod/bedrijf-6096-id3996-stijlvolle-horecazaak-met-terras-aan-de-buitenveldertelaan-amsterdam",
        "fastFoodDoner": "Yes",
        "casualDiningKebab": "No"
    },
    {
        "id": 10,
        "title": "Amstelstraat 26 (Large Casco)",
        "neighborhood": "Amsterdam Centrum",
        "surroundings": "Near Rembrandtplein, extremely high nightlife traffic.",
        "rent": "\u20ac 13.333 / mo",
        "takeover": "Casco",
        "size": "350 m\u00b2",
        "rentableSpace": "Divided over ground floor, mezzanine, and basement.",
        "suitability": "Low",
        "suitClass": "suit-moderate",
        "description": "Extremely high rent and massive size. Only suitable for a massive flagship restaurant or club, not a standard kebab shop.",
        "lat": 52.3660776,
        "lng": 4.8995135,
        "link": "https://duijnhorecamakelaars.nl/aanbod/casco-horecaruimte-aan-de-amstelstraat-in-amsterdam/",
        "fastFoodDoner": "Yes",
        "casualDiningKebab": "Yes",
        "isFavorite": true
    },
    {
        "id": 11,
        "title": "Amstelveenseweg 71",
        "neighborhood": "Amsterdam Zuid",
        "surroundings": "Well-visited section near Vondelpark. Strong retail mix.",
        "rent": "\u20ac 4.300 / mo",
        "takeover": "\u20ac 45.000",
        "size": "~ 50 seats",
        "rentableSpace": "Seating at front, bar in middle, kitchen at back.",
        "suitability": "High",
        "suitClass": "suit-high",
        "description": "Low takeover for a prime area. Very standard layout perfectly suited for fast-casual dining.",
        "lat": 52.3535812,
        "lng": 4.8560377,
        "link": "https://duijnhorecamakelaars.nl/aanbod/complete-horecazaak-aan-bekende-straat-in-amsterdam-zuid/",
        "fastFoodDoner": "Yes",
        "casualDiningKebab": "Yes",
        "isFavorite": true
    },
    {
        "id": 13,
        "title": "Linnaeusstraat 18 H",
        "neighborhood": "Amsterdam Oost",
        "surroundings": "Lively street with constant passing traffic.",
        "rent": "\u20ac 4.613 / mo",
        "takeover": "\u20ac 85.000",
        "size": "381 m\u00b2",
        "rentableSpace": "Very large, fits 50+ guests, potential for 8 terrace seats.",
        "suitability": "Moderate",
        "suitClass": "suit-moderate",
        "description": "Unusually large for a standard doner shop. Better suited for a large-scale Turkish dining restaurant.",
        "lat": 52.3619144,
        "lng": 4.9247465,
        "link": "https://adhoc-horecamakelaars.nl/bedrijfsaanbod/huur/amsterdam/linnaeusstraat-18-h-amsterdam",
        "fastFoodDoner": "No",
        "casualDiningKebab": "Yes"
    }
];
